### ISSUE TITLE
How Do you link the pdf file?

### ISSUE THREAD

**Issue by josuevalrob** [ajnyga/tsvConverter#1]
I was checking your xlsx example. I dont found any url for attach a PDF file.

**Comment by ajnyga** [comment]
Hi,
I have only used local files, an example should be in the xlsx file. Basically you save all the files to a folder below the script and give the name of the folder in the settings. 

It would be maybe fairly easy to alter the code so that if the filename had an url instead, it would fetch the file.

ps. I am doing some additional changes to the plugin, better support for content with multiple locales...
